live:
  - name: ethereum-live-testnet
    networks:
      - name: Sepolia-b6-infura
        id: sepolia-b6-infura
        chainid: 11155111
        host: https://sepolia.infura.io/v3/87c381c41fab413292c965db3323cf0a
        explorer: https://api-sepolia.etherscan.io/api